services:
  mysql:
    image: mysql:8.0.41-bookworm
    container_name: delivery-mysql
    ports:
      - "33061:3306"
    env_file:
      - ./envs/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4.2-alpine
    container_name: delivery-redis
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4.0.8-alpine
    container_name: delivery-rabbitmq
    ports:
      - "56720:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    image: delivery-api:latest
    container_name: delivery-api
    ports:
      - "8000:8000"
    env_file:
      - ./envs/delivery.env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ./src:/app/src

  tests:
    build:
      context: .
      dockerfile: docker/tests.Dockerfile
    image: delivery-tests:latest
    container_name: delivery-tests
    env_file:
      - ./envs/delivery.env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

  celery:
    build:
      context: .
      dockerfile: docker/celery.Dockerfile
    image: delivery-celery:latest
    container_name: delivery-celery
    env_file:
      - ./envs/delivery.env
    depends_on:
      - rabbitmq
      - redis
      - mysql
      - api
    volumes:
      - ./src:/app/src

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  default:
    name: delivery-network
